### ISSUE TITLE
glViewport wont scale on HDPI Displays

### ISSUE THREAD

**Issue by Guerra24** [Guerra24/Voxel#33]
The game internal screen have 1/4 of the real window size.

**Comment by danirod** [comment]
Finally got the chance to test support on HiDPI Windows.
- Mouse offsets when the scale is set to anything greater than 100%. For example, in the following screenshot the Exit button is hovered although the mouse cursor is actually slightly above the button.

![captura de pantalla 22](https://cloud.githubusercontent.com/assets/1568690/12385551/b06f3642-bdbd-11e5-9c70-73a069a2e87f.png)
- Some GUI elements aren't visible when the DPI is set to higher values. The following screenshot was taken with a DPI value of 175%.

![captura de pantalla 21](https://cloud.githubusercontent.com/assets/1568690/12385571/ea981cbc-bdbd-11e5-8796-70f861e891a6.png)

**Comment by Guerra24** [comment]
Fixed on Mac/OSX.

**Comment by Guerra24** [comment]
Fixed on Mac/OSX.

**Comment by danirod** [comment]
New reports on HiDPI Support.
- OS: Windows 10
- Hardware: MacBook Pro
- Graphics card: Intel Iris Pro 5200
- Windows DPI Scale: 200%

It is interesting to see that when scaling on 200% the Voxel graphics scale correctly. Mouse pointer is on the correct location, the buttons only hover when the square IS actually over it. I have just tested this again **using the same launcher** on 175% and 150% scale and it offsets. This could mean that Voxel has issues rounding numbers when the scale is not an integer number (1.5, 1.75 instead of 2.0).

![img_27012016_092432](https://cloud.githubusercontent.com/assets/1568690/12607989/3e9445c6-c4d9-11e5-8d7f-ac995accadd0.png)

The water doesn't look very bad.

![img_27012016_092549](https://cloud.githubusercontent.com/assets/1568690/12608051/ae9ae7b2-c4d9-11e5-8dd0-258168dc681e.png)

However, the sky does. I have the same issues than the ones I had on MacOS X, it looks like a non-working TV showing noise. I cannot show it in the screenshot because for some reason it fixes  when I press Print Screen, but it still happens. (_**EDIT__: it is actually visible, zoom the following screenshot and you'll see weird dots all over the sky_). The fact that it happens on Windows as well makes me thing that it is not the OS, but the graphics card, since this is a dualbooted MacBook Pro.

![img_27012016_092534](https://cloud.githubusercontent.com/assets/1568690/12608074/d9ca0922-c4d9-11e5-8849-f8088eb360da.png)
